urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    (r'^list/$', 'apps.office.cars.views.car_list'), #车辆信息列表 /office/cars/list/
    (r'^add', 'apps.office.cars.views.car_add'), #添加车辆信息/office/cars/add
    (r'^edit', 'apps.office.cars.views.car_edit'), #修改车辆信息 /office/cars/edit/
    (r'^dele', 'apps.office.cars.views.car_del'), #删除车辆信息 /office/cars/dele
    #车辆使用
    (r'^ulist/$', 'apps.office.cars.views.userecord_list'), #车辆使用记录 /office/cars/ulist/
    (r'^uedit', 'apps.office.cars.views.userecord_edit'), #增加、修改使用记录 /office/cars/uedit
    (r'^sel', 'apps.office.cars.views.sel'),#列表中级联查找/office/cars/sel
    #费用记录
    (r'^clist/$', 'apps.office.cars.views.costrecord_list'), #费用记录浏览 /office/cars/clist/
    (r'^cedit', 'apps.office.cars.views.costrecord_edit'), #增加、修改使用记录 /office/cars/cedit
     (r'^gtime/$', 'apps.office.cars.views.gtime'),
)

models.py
# -*- coding:utf-8 -*-

from django.db import models
from apps import utils, Departs
from apps.models import Users


class Cars(models.Model):
    """
    描述：车辆信息模型
    作者：凯伦kevin
    """

    STATU_CHOICE = (
        (0, '空闲中'),
        (1, '使用中'),
    )

    un_id = models.IntegerField(u'机构编号', db_column='un_id', blank=True, null=True) #机构编号，由session写入
    car = models.CharField(u'车牌号', max_length=10)
    brand = models.CharField(u'车辆品牌',max_length=20, blank=True, null=True)
    site = models.IntegerField(u'座位数', max_length=2, blank=True, null=True)
    path = models.ImageField(u'车辆图片',upload_to='/', blank=True, null=True)
    company = models.CharField(u'保险公司', max_length=30, blank=True, null=True)
    time = models.DateTimeField(u'投保时间', blank=True, null=True)
    person = models.CharField(u'经办人', max_length=5, blank=True, null=True)
    statu = models.IntegerField(u'使用状态',choices=STATU_CHOICE, blank=True, null=True)

    adder = models.CharField(u'添加人', max_length = 100) #添加人(id)姓名
    #系统保留信息
    addtime = models.DateTimeField(auto_now_add = True) #添加时间
    adderip = models.IPAddressField(default = u'0.0.0.0') #添加人当前IP地址
    status  = models.IntegerField(choices = utils.CHOICES_STATUS, default = 200) #状态；0：逻辑删除；200：正常；

    class Meta:
        db_table = 'office_cars'

class UseRecord(models.Model):
    """
    描述：车辆使用记录
    作者：凯伦kevin
    """

    user = models.ForeignKey(Users, verbose_name = u'申请人')
    depart = models.ForeignKey(Departs, verbose_name = u'申请部门')
    car = models.ForeignKey(Cars, verbose_name = u'借用车辆')
    stime = models.DateTimeField(u'借用时间', blank=True, null=True)
    ltime = models.DateTimeField(u'归还时间', blank=True, null=True)
    use = models.CharField(u'用途', blank=True, null=True, max_length=50)
    mileage = models.DecimalField(u'里程', max_digits=12, decimal_places=2, blank=True, null=True)
    oilwear = models.DecimalField(u'油耗', max_digits=12, decimal_places=2, blank=True, null=True)
    remarks = models.CharField(u'备注', blank=True, null=True, max_length=100)

    #系统保留信息
    un_id = models.IntegerField(u'机构编号', db_column='un_id', blank=True, null=True) #机构编号，由session写入
    adder = models.CharField(u'添加人', max_length = 100) #添加人(id)姓名
    addtime = models.DateTimeField(auto_now_add = True) #添加时间

    adderip = models.IPAddressField(default = u'0.0.0.0') #添加人当前IP地址

    class Meta:
        db_table = 'office_userecord'

class CostRecord(models.Model):
    """
    描述：车辆费用记录
    作者：凯伦kevin
    """

    SERVICE_CHOICE = (
        (0, '加油'),
        (1, '维修'),
        (2, '保养'),
        (3, '保险'),
        (4, '其他'),
    )
    car = models.ForeignKey(Cars, verbose_name = u'车辆')
    stype = models.IntegerField(u'服务类型',choices=SERVICE_CHOICE, blank=True, null=True)
    stime = models.DateTimeField(u'时间', blank=True, null=True)
    cost = models.DecimalField(u'费用', max_digits=12, decimal_places=2, blank=True, null=True)
    user = models.ForeignKey(Users, verbose_name = u'经办人')
    remarks = models.CharField(u'备注', blank=True, null=True, max_length=100)
    depart = models.ForeignKey(Departs, verbose_name = u'申请部门')
    #系统保留信息
    un_id = models.IntegerField(u'机构编号', db_column='un_id', blank=True, null=True) #机构编号，由session写入
    adder = models.CharField(u'添加人', max_length = 100) #添加人(id)姓名
    addtime = models.DateTimeField(auto_now_add = True) #添加时间
    adderip = models.IPAddressField(default = u'0.0.0.0') #添加人当前IP地址

    class Meta:
        db_table = 'office_costrecord'

templates/cars_del.html
<hgroup>
    <h3>提示:</h3>
    <form action="/office/cars/dele?method=delete" method="post">
        <p>您正要删除以下内容: </p>
        {% for c in cars %}
            <ul>
                <li><input type="checkbox" name="id" id="{{c.id}}" value="{{c.id}}" checked />
                    <label for="{{c.id}}">名称:[{{c.car}}]的资源?</label></li>
            </ul>
        {% endfor %}
        <p>您确定要执行此操作么？</p>
        <article>
            <span></span>
            <input type="submit" class="submit" value="确定" />
            <input type="button" class="submit" value="取消" id="close" />
        </article>
    </form>
</hgroup>

templates/cars_edit.html
{% extends 'base.html' %}

{% block head_style %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="/script/skins/zTreeStyle.css" />
    <link rel="stylesheet" href="/script/jscal/css/erp/erp.css" />
    <link rel="stylesheet" type="text/css" href="/script/jscal/css/jscal2.css" />
{% endblock %}

{% block head_script %}
    {{ block.super }}
    <script type="text/javascript" src="/script/validation/jquery.validate.min.js"></script>
    <script type="text/javascript" src="/script/editor/ckeditor.js"></script>
    <script type="text/javascript" src="/script/jscal/jscal2.js"></script>
    <script type="text/javascript" src="/script/jscal/lang/cn.js"></script>
    <script type="text/javascript">

    </script>
    <script type="text/javascript">
        $(document).ready(function(){
            $("#mainform").validate({
                errorPlacement: function(error, element) {
                    var msg = error.text();
                    $(element).parents('article').find('span.error').html('<label>'+msg+'</label>');
                    //error.text().appendTo(element.parent().find('.error'));
                },
                success: function(element) {
                    $(element).parents('article').find('span.error').html('');
                },
                rules: {
                    car: {
                        required: true
                    },
                    site:{
                        required: true
                    },
                    company:{
                        required: true
                    },
                    time:'required',
                    person:'required',
                    unit:'required',
                    statu:'required'
                },
                messages: {
                    car:{
                        required: '请填写车牌号！'
                    },
                    site:{
                        required: '请填写车辆座位数！'
                    },
                    company:{
                        required: '请填写投保公司名称！'
                    },
                    time:{
                        required:'请选择投保时间！'
                    },
                    person:{
                        required:'请填写经办人！'
                    },
                    unit:{
                        required:'请选择车辆所属机构！'
                    },
                    statu:{
                        required:'请选择车辆使用状态！'
                    }
                }
            });
        });
    </script>
{% endblock %}

{% block body_contents %}
    <section id="editor-console">
        <hgroup>
            <form id= 'mainform' enctype="multipart/form-data" action="" method="post">
                <article>
                    <span>车牌号：</span>
                    {{ form.car }}
                    <span class="help">{{ form.car.help_text }}</span>
                    <span class="error">{{ form.car.errors.as_text }}</span>
                </article>
                <article>
                    <span>汽车品牌：</span>
                    {{ form.brand }}
                    <span class="help">{{ form.brand.help_text }}</span>
                    <span class="error">{{ form.brand.errors.as_text }}</span>
                </article>
                <article>
                    <span>座位数：</span>
                    {{ form.site }}
                    <span class="help">{{ form.site.help_text }}</span>
                    <span class="error">{{ form.site.errors.as_text }}</span>
                </article>
                {%if instance.path != '' %}
                    <article>
                        <span>车辆图片 ：</span>
                        <a href="{{ form.path.value }}">【查看】</a>
                    </article>
                    <article>
                        <span>更新文件 ：</span>
                        <input type="file" name="file" id="id_path" />
                        <span class="help">请上传jpg文件..</span>
                        <span class="error">{{form.path.errors.as_text}}</span>
                    </article>
                {% else %}
                    <article>
                        <span>车辆图片 ：</span>
                        <input type="file" name="file" value="浏览">
                        <span class="help">请上传jpg文件..</span>
                        <span class="error">{{forms.path.errors.as_text}}</span>
                    </article>
                {% endif %}
                <article>
                    <span>保险公司：</span>
                    {{ form.company }}
                    <span class="help">{{ form.company.help_text }}</span>
                    <span class="error">{{ form.company.errors.as_text }}</span>
                </article>
                <article>
                    <span>投保时间：</span>
                    {{ form.time }}
                    <img src="/images/ico-11.gif" id="id_img_time">
                    <script type="text/javascript">
                        Calendar.setup({
                            inputField    : "id_time",
                            trigger       : "id_img_time",
                            showTime      : 24,
                            dateFormat    : "%Y-%m-%d",
                            onSelect:function(){this.hide();}
                        });
                    </script>
                    <span class="help">{{ form.time.help_text }}</span>
                    <span class="error">{{ form.time.errors.as_text }}</span>
                </article>
                <article>
                    <span>经办人：</span>
                    {{ form.person }}
                    <span class="help">{{ form.person.help_text }}</span>
                    <span class="error">{{ form.person.errors.as_text }}</span>
                </article>
                <article>
                    <span>所属机构：</span>
                    <select name="unit" id="unit">
                        <option value="">===请选择机构===</option>
                        {% for unit in units %}
                            <option value="{{unit.id}}" {% if unitid == unit.id %} selected {% endif %}>{{unit.name}}</option>
                        {% endfor %}
                    </select>
                    <span class="help"></span>
                    <span class="error"></span>
                </article>
                <article>
                    <span>使用状态：</span>
                    {{ form.statu }}
                    <span class="help">{{ form.statu.help_text }}</span>
                    <span class="error">{{ form.statu.errors.as_text }}</span>
                </article>
                <article style="padding-left: 150px">
                    <input type="submit" class="button"   value="修改"  />
                </article>
            </form>
        </hgroup>
    </section>
{% endblock %}

templates/cars_list.html
{% extends 'base.html' %}

{% block body_header_fixed %} class="fixed"{% endblock %}
{% block head_style %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="/script/skins/ui1007s.css"/>
    <link rel="stylesheet" type="text/css" href="/script/jscal/css/jscal2.css" />
{% endblock%}

{% block head_script %}
    {{ block.super }}
    <script type="text/javascript" src="/script/jscal/jscal2.js"></script>
    <script type="text/javascript" src="/script/jscal/lang/cn.js"></script>
{% endblock %}

{% block body_search %}
    <section id="serach-console">
        <hgroup>
            <form action="?method=search" method="get">
                搜索
                <select name="keytype" id="keytype">
                    <option value="1"{% if search.keytype == "1" %} selected="selected" {%endif%}>车牌号</option>
                    <option value="2"{% if search.keytype == "2" %} selected="selected" {%endif%}>品牌</option>
                    <option value="3"{% if search.keytype == "3" %} selected="selected" {%endif%}>座位数</option>
                </select>
                中包含
                <input name="keyword" type="text" value = "{{serach.keyword}}" />
                使用状态为{{ search.s }}
                <select name="statu" >
                    <option value="" {% if search.statu == '' %} selected="selected" {%endif%}>全部</option>
                    <option value="0" {% if search.statu == '0' %} selected="selected" {%endif%}>空闲中</option>
                    <option value="1" {% if search.statu == '1' %} selected="selected" {%endif%}>使用中</option>
                </select>

                <input class="button" type="submit" value="搜索" />
            </form>

        </hgroup>
    </section>
{% endblock %}

{% block body_contents %}
    <section id="editor-console">
        {% load pagination_tags %}
        <table class="data-list" width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <th width="2%"><input type="checkbox" id="check-console" value="-1"></th>
                <th width="10%">车牌号</th>
                <th width="10%">品牌</th>
                <th width="10%">座位数</th>
                <th width="10%">图片</th>
                <th width="10%">保险公司</th>
                <th width="10%">投保时间</th>
                <th width="10%">经办人</th>
                <th width="10%">使用状态</th>
            </tr>
            {% if querys %}
                {% autopaginate querys 30 %}
                {% for q in querys %}
                    <tr>
                        <td><input type="checkbox" name="id" id="{{q.id}}" value="{{ q.id }}"></td>
                        <td align="center">{{q.car}}</td>
                        <td align="center">{{q.brand}}</td>
                        <td align="center">{{q.site}}</td>
                        <td align="center">
                            {% if q.path != '' %}
                                <a href="{{ q.path }}" target="_blank"><img src="{{ q.path }}" width="40px" height="30px"></a>
                            {% endif %}
                        </td>
                        <td align="center">{{q.company}}</td>
                        <td align="center">{{q.time|date:'Y-m-d'}}</td>
                        <td align="center">{{q.person}}</td>
                        <td align="center">{{q.get_statu_display}}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="9" style="color:#e00">空记录！</td>
                </tr>
            {% endif %}
        </table>
        <div >{% paginate %}</div>
        <br/>
    </section>
{% endblock %}

templates/costrecord_list.html
{% extends 'base.html' %}

{% block body_header_fixed %} class="fixed"{% endblock %}
{% block head_style %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="/script/skins/ui1007s.css"/>
    <link rel="stylesheet" type="text/css" href="/script/jscal/css/jscal2.css" />
{% endblock%}

{% block head_script %}
    {{ block.super }}
    <script type="text/javascript" src="/script/jscal/jscal2.js"></script>
    <script type="text/javascript" src="/script/jscal/lang/cn.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $("#keytype").change(function(){
                var keytype = $(this).val();
                var keyword = $('#keyword');
                keyword.empty();
                keyword.append('<option value="">请选择</option>');
                if(keytype == 1){
                    $.post("/office/cars/sel", { "keytype":$(this).val() },function(data){
                        $.each(data,function(id,option){
                            html = '<option value="'+ option.id +'">' + '['+option.uname+']'+option.name + '</option>';
                            keyword.append(html);
                        });
                    }, "json");
                }
                else{
                    $.post("/office/cars/sel", { "keytype":$(this).val() },function(data){
                        $.each(data,function(id,option){
                            var s = {{ cars.id }}
                                    html = '<option value="'+ option.id +'"';
                            if (option.id == s) {
                                html += ' selected';
                            }
                            html += '>' + option.name + '</option>';
                            keyword.append(html);
                        });
                    }, "json");
                }
            }).change();
        });
    </script>
{% endblock %}

{% block body_search %}
    <section id="serach-console">
        <hgroup>
            <form action="?method=search" method="get">
                搜索
                <select name="keytype" id="keytype">
                    <option value="1"{% if search.keytype == "1" %} selected="selected" {%endif%}>部门</option>
                    <option value="2"{% if search.keytype == "2" %} selected="selected" {%endif%}>车辆</option>
                </select>
                为
                <select name="keyword" id="keyword">
                    <option value="">全部</option>
                </select>
                <input class="button" type="submit" value="搜索" />
            </form>
        </hgroup>
    </section>
{% endblock %}

{% block body_contents %}
    <section id="editor-console">
        {% load pagination_tags %}
        <table class="data-list" width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr>
                <th width="2%"><input type="checkbox" id="check-console" value="-1"></th>
                <th width="10%">车辆</th>
                <th width="10%">服务类型</th>
                <th width="10%">费用</th>
                <th width="10%">时间</th>
                <th width="10%">经办人</th>
                <th width="10%">备注</th>
            </tr>
            {% if querys %}
                {% autopaginate querys 30 %}
                {% for q in querys %}
                    <tr>
                        <td><input type="checkbox" name="id" id="{{q.id}}" value="{{ q.id }}"></td>
                        <td align="center">{{q.car.car}}</td>
                        <td align="center">{{q.get_stype_display}}</td>
                        <td align="center">{{q.cost}}</td>
                        <td align="center">{{q.stime|date:'Y-m-d H:i'}}</td>
                        <td align="center">{{q.user}}</td>
                        <td align="center">{{q.remarks}}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="10" style="color:#e00">空记录！</td>
                </tr>
            {% endif %}
        </table>
        <div >{% paginate %}</div>
        <br/>
    </section>
{% endblock %}

templates/userecord_edit.html
{% extends 'base.html' %}

{% block head_style %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="/script/jscal/css/jscal2.css" />
{% endblock %}

{% block head_script %}
    {{ block.super }}
    <script type="text/javascript" src="/script/validation/jquery.validate.min.js"></script>
    <script type="text/javascript" src="/script/jscal/jscal2.js"></script>
    <script type="text/javascript" src="/script/jscal/lang/cn.js"></script>
    <script type="text/javascript">

    </script>
    <script type="text/javascript">
    function strtotimestamp(datestr)
      {
          var new_str = datestr.replace(/:/g,"-");
          new_str = new_str.replace(/ /g,"-");
          var arr = new_str.split("-");
          var datum = new Date(Date.UTC(arr[0],arr[1]-1,arr[2],arr[3],arr[4],arr[5]));

          return (datum.getTime()/1000);  //为PHP所用
       }
        $(document).ready(function(){

            $("#depart").change(function(){
                var staffid = $('#user');
                staffid.empty();
                staffid.append('<option value="">请选择员工</option>');
                var selectDepart=$(this).val();
                if(selectDepart=='') return;
                $.post("/hr/personlist/", { "deid": selectDepart, 'main':1 },function(data){
                    $.each(data,function(id,option){
                        var s = parseInt('{{ form.user.value}}');
                        var res = '';
                        if(s == option.id){
                            res = 'selected';
                        }
                        var html = '<option value="'+ option.id +'" '+res+'>' + option.realname + '</option>';
                        staffid.append(html);
                    });
                }, "json");
            }).change();

            if('{{ form.user.value}}'=='None'||'{{ form.user.value}}'=='')
            {
                //用户申请
                $('#id_stime').attr("readonly","readonly");
                $('#id_ltime').attr("disabled","disabled");
                $('#id_mileage').attr("disabled","disabled");
                $('#id_oilwear').attr("disabled","disabled");
               // $('#id_stime').val(new date());
                $('#ltime').hide();

                 $("#mainform").validate({
                    errorPlacement: function(error, element) {
                        var msg = error.text();
                        $(element).parents('article').find('span.error').html('<label>'+msg+'</label>');
                        //error.text().appendTo(element.parent().find('.error'));
                    },
                    success: function(element) {
                        $(element).parents('article').find('span.error').html('');
                    },
                    rules: {
                        depart:'required',
                        user:'required',
                        car:'required',
                        stime:'required',
                        //ltime:'required',
                        use:'required'
                        //mileage:'required',
                        //oilwear:'required'
                    },
                    messages: {
                        depart:{
                            required: '请选择申请部门！'
                        },
                        user:{
                            required: '请选择申请人！'
                        },
                        car:{
                            required: '请选择借用的车辆！'
                        },
                        stime:{
                            required:'请选择借用时间！'
                        },
                       // ltime:{
                       //     required:'请选择归还时间！'
                       // },
                        use:{
                            required:'请填写用途！'
                        }
                       // mileage:{
                       //     required:'请填写里程数！'
                      //  },
                      //  oilwear:{
                     //       required:'请填写油耗数！'
                     //   }
                    }
                });


            }
            else
            {
                //修改
                $('#stime').hide();
                $('#id_stime').attr("disabled","disabled");
                $('#id_ltime').attr("readonly","readonly");
                $('#depart').attr("disabled","disabled");
                $('#user').attr("disabled","disabled");
                $('#car').attr("disabled","disabled");
                $('#id_use').attr("disabled","disabled");


                 $("#mainform").validate({
                    errorPlacement: function(error, element) {
                        var msg = error.text();
                        $(element).parents('article').find('span.error').html('<label>'+msg+'</label>');
                        //error.text().appendTo(element.parent().find('.error'));
                    },
                    success: function(element) {
                        $(element).parents('article').find('span.error').html('');
                    },
                    rules: {
                        ltime:{required:true},
                        mileage:{required:true,number:true},
                        oilwear:{required:true,number:true}
                    },
                    messages: {
                        ltime:{
                            required:'请选择归还时间！'
                        },
                        mileage:{
                            required:'请填写里程数！',
                            number:'请输入数字'
                        },
                        oilwear:{
                            required:'请填写油耗数！',
                            number:'请输入数字'
                        }
                    }
                });

            }


        });
    </script>
{% endblock %}

{% block body_contents %}
    <section id="editor-console">
        <hgroup>
            <form id= 'mainform' enctype="multipart/form-data" action="" method="POST">
                <article id="allp">
                    <span>申请借用：</span>
                    <select name="depart" id="depart">
                        <option value="">请选择部门</option>
                        {% for d in departs %}
                            <option value="{{ d.id }}" {% if form.depart.value == d.id %} selected {% endif %}>{{ d.dep_list_name|safe }}
                            </option>
                        {% endfor %}
                    </select>&nbsp;
                    <select name="user" id="user">
                        <option value="">请选择员工</option>
                    </select>
                    <span class="help">{{ field.help_text }}</span>
                    <span class="error">{{ field.errors.as_text }}</span>
                </article>
                <article>
                    <span>借用车辆：</span>
                    <select name="car" id="car">
                        <option value="">请选择要借用的车辆</option>
                        {% for c in cars %}
                            <option value="{{c.id}}" {% if form.car.value == c.id %} selected {% endif %}>{{c.car}}</option>
                        {% endfor %}
                    </select>
                    <span class="help"></span>
                    <span class="error"></span>
                </article>
                <article>
                    <span>借用时间：</span>
                    {{ form.stime }}
                    <img src="/images/ico-11.gif" id="stime">
                    <script type="text/javascript">
                        Calendar.setup({
                            inputField    : "id_stime",
                            trigger       : "stime",
                            showTime      : 24,
                            min            :new Date(),

                            dateFormat    : "%Y-%m-%d %H:%M:%S",
                            onSelect:function(){this.hide();}
                        });
                    </script>
                    <span class="help">{{ form.stime.help_text }}</span>
                    <span class="error">{{ form.stime.errors.as_text }}</span>
                </article>
                <article>
                    <span>归还时间：</span>
                    {{ form.ltime }}
                    <img src="/images/ico-11.gif" id="ltime">
                    <script type="text/javascript">
                        Calendar.setup({
                            inputField    : "id_ltime",
                            trigger       : "ltime",
                            showTime      : 24,
                            min            :new Date(),
                            onTimeChange  : function(cal) {
                            var ss=strtotimestamp($("#id_stime").val());
                            var hh=strtotimestamp($("#id_ltime").val());
                            if(ss>hh) $("#id_ltime").val('');

                            },
                            dateFormat    : "%Y-%m-%d %H:%M:%S",
                            onSelect:function(){this.hide();}
                        });
                    </script>
                    <span class="help">{{ form.ltime.help_text }}</span>
                    <span class="error">{{ form.ltime.errors.as_text }}</span>
                </article>
                <article>
                    <span>用途：</span>
                    {{ form.use }}
                    <span class="help">{{ form.use.help_text }}</span>
                    <span class="error">{{ form.use.errors.as_text }}</span>
                </article>
                <article>
                    <span>里程：</span>
                    {{ form.mileage }}km
                    <span class="help">{{ form.mileage.help_text }}</span>
                    <span class="error">{{ form.mileage.errors.as_text }}</span>
                </article>
                <article>
                    <span>油耗：</span>
                    {{ form.oilwear }}L
                    <span class="help">{{ form.oilwear.help_text }}</span>
                    <span class="error">{{ form.oilwear.errors.as_text }}</span>
                </article>
                <article>
                    <span>备注：</span>
                    {{ form.remarks }}
                    <span class="help">{{ form.remarks.help_text }}</span>
                    <span class="error">{{ form.remarks.errors.as_text }}</span>
                </article>
                <article style="padding-left: 150px">
                    <input type="submit" class="button"   value="保存"  />
                </article>
            </form>
        </hgroup>
    </section>
{% endblock %}